### ISSUE TITLE
Suggestion/bug fix config option to disable placing of backpacks in the world!

### ISSUE THREAD

**Issue by SirAron111** [DreenDex/ImprovedBackpacks-Issues#20] opened 2019-10-25 14:17 UTC
Suggestion/bug fix config option to disable placing of backpacks in the world!

There needs to be an option in the config to prevent placing of backpacks into the world. I love the mod it works so great there is just one problem. If you place a backpack into the world it can cause the game to freeze up or crash in various mod combinations.

The Bugs causing crashes or freezes etc with this feature should ofc be fixed?

But for now a config option to dimply prevent placing them should be enough it will also enable (Modpack makers like me for example to disable this feature to unlock it later or simple prevent unintentional uses of backpacks as blocks etc.)

GZ
SirAron

**Comment by qchronod** [comment] 2020-03-02 03:40
I'd like to second this suggestion.
Just spent the last few hours trying to figure out why the backups on my M.C.Eternal 1.3.3 server weren't actually running (it would start the backup but never save anything)
Long story short, one of the players picked up his backpack he was using as temp storage while building some machines and then the backups started completing again.

The only errors that we were seeing in the logs contained:
Caused by: java.lang.StackOverflowError
    at java.io.DataOutputStream.write(Unknown Source)
    at java.io.DataOutputStream.writeUTF(Unknown Source)
    at java.io.DataOutputStream.writeUTF(Unknown Source)
    at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:474)
    at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35)
    at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:475)
(with the last two lines repeating 500 times)
So I think that the bag was trying to save the NBT of itself into it's own NBT that contained the NBT of itself.... ad infinitum.

**Comment by socolio** [comment] 2020-04-01 15:13
Sorry for lags. It will be fixed in 1.5.0.0. Also option to disable backpack placing will be added in this version.

**Closed by socolio** 2020-04-01 15:13 UTC
